Fix race condition in objectset handover integration tests by moving  assertions that should happen after the new object set becomes available after the code that waits for it to become available.
Previous to this fix, testing a cpu-starved PKO would often result in a failure when the tests asserted that object had already fully been handed over, when pko only had reported that the new object set was already created and unavailable due to failing probes on an already existing object.

```
    hypershift_test.go:91:
        	Error Trace:	/home/erdii/projects/redhat/github.com/package-operator/package-operator/integration/package-operator/objectset_test.go:763
        	           				/home/erdii/projects/redhat/github.com/package-operator/package-operator/integration/package-operator/objectset_test.go:505
        	           				/home/erdii/projects/redhat/github.com/package-operator/package-operator/integration/package-operator/hypershift_test.go:91
        	Error:      	Should be true
        	Test:       	TestHyperShift/ObjectSetHandover
        	Messages:   	controller name of default-test-hc/cm-1 not prefixed with test-rev2
--- FAIL: TestHyperShift (74.36s)
    --- PASS: TestHyperShift/HyperShift_Installation (1.11s)
    --- PASS: TestHyperShift/ObjectSetSetupPauseTeardown (17.16s)
    --- FAIL: TestHyperShift/ObjectSetHandover (2.04s)
FAIL
```

PS: why does `go mod tidy` bump a dependency here?
Signed-off-by: Josh Gwosdz <jgwosdz@redhat.com>